Also look for mpg123 if we can't find mpg321
darcs-hash:af0f9805d3cac0b311a9aca685e7f5bf84cbc60f

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1290,9 +1290,50 @@ echo "${ECHO_T}no" >&6
 fi
 
 if test -z "$MPG321" ; then
-	{ { echo "$as_me:$LINENO: error: You need mpg321 installed to run hmp3" >&5
-echo "$as_me: error: You need mpg321 installed to run hmp3" >&2;}
+    # Extract the first word of "mpg123", so it can be a program name with args.
+set dummy mpg123; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_path_MPG321+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $MPG321 in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_MPG321="$MPG321" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_path_MPG321="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+  ;;
+esac
+fi
+MPG321=$ac_cv_path_MPG321
+
+if test -n "$MPG321"; then
+  echo "$as_me:$LINENO: result: $MPG321" >&5
+echo "${ECHO_T}$MPG321" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+    if test -z "$MPG321" ; then
+	    { { echo "$as_me:$LINENO: error: You need mpg321 or mpg123 installed to run hmp3" >&5
+echo "$as_me: error: You need mpg321 or mpg123 installed to run hmp3" >&2;}
    { (exit 1); exit 1; }; }
+    fi
 fi
 
 cat >>confdefs.h <<_ACEOF
